config/routes.rb
Rails.application.routes.draw do
  resources :tools

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get 'dashboard/index'
  devise_for :users
  resources :users
  resources :timecards #do

  get "clock_out", to: "timecards#clock_out"
  get "clock_in", to: "timecards#clock_in"

  root 'home#index'

end

app/models/tool.rb
class Tool < ActiveRecord::Base
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  def index
    @tools = Tool.all
  end

  def show
  end

  def new
    @tool = Tool.new
  end

  def create
    @tool = Tool.new(tool_prams)
    if @tool.save
      redirect_to tools_path
    else
      render :new
    end
  end

  private

  def tool_prams
    #TODO add params
    # params.require(:user_id,)
    params.require(:tool).permit(:name, :quantity, :brand, :kind, :mill, :lathe,
      :drill, :diameter, :length, :drill_length, :radius, :material, :teeth, :f_low,
      :f_high, :f_rough, :f_finish, :fZ_low, :fZ_high, :fZ_rough, :fZ_finish, :Vc_low,
      :Vc_high,)
  end
end

app/helpers/tools_helper.rb
module ToolsHelper
end

app/views/tools/index.html.haml
-# %div{:class => "w3-container>"}
%div
  %h1.center-align Tools#index
  ="tool count: #{@tools.count}"
  %p i can be clicked away
  %br
  %table.highlight.cenered
    %thead
      %tr
        %th
        %th name
        %th quantity
        %th kind
        %th brand
        %th IPT low
    - i=1
    -@tools.each do |tool|
      %tr
        %td
          ="#{i})"
        %td
          =tool.name
        %td
          =tool.quantity
        %td
          =tool.kind
        %td
          =tool.brand
        %td
          =tool.fZ_low
        - i=i+1

  = button_to 'new tools', new_tool_path, :class =>"btn", :method => :get

app/views/tools/new.html.haml
%h1 Add a new tool

%button#myBtn{:onclick => "endmill()", :type => "button"} Endmill
%button#myBtn{:onclick => "turningTools()", :type => "button"} Turning
%button#myBtn{:onclick => "drill()", :type => "button"} Drill
%button#myBtn{:onclick => "toolHolder()", :type => "button"} Tool Holders

#endmillForm{:style => "display:none",}
  %h1 Endmill
  = form_for @tool do |t|
    =t.hidden_field :mill, :value => true

    =t.label :name
    =t.text_field :name

    = t.label :kind
    %br
    %br
    = t.radio_button :kind, 'flat'
    = t.label :kind, 'Flat', :value => 'Flat'
    = t.radio_button :kind, 'ball'
    = t.label :kind, 'Ball', :value => 'Ball'
    %br
    %br
    =t.label :brand
    =t.text_field :brand

    =t.label :quantity
    =t.text_field :quantity

    =t.label :diameter
    =t.text_field :diameter

    =t.label :length
    =t.text_field :length

    =t.label :teeth
    =t.text_field :teeth

    =t.label :fZ_low
    =t.text_field :fZ_low

    =t.label :fZ_high
    =t.text_field :fZ_high

    =t.label :fZ_rough
    =t.text_field :fZ_rough

    =t.label :fZ_finish
    =t.text_field :fZ_finish

    =t.label :Vc_low
    =t.text_field :Vc_low

    =t.label :Vc_high
    =t.text_field :Vc_high

    =t.label :Vc_rough
    =t.text_field :Vc_rough

    =t.label :Vc_finish
    =t.text_field :Vc_finish

    =t.submit

#turningToolsForm{:style => "display:none",}
  %h1 Turning Tools
  = form_for @tool do |t|
    =t.hidden_field :lathe, :value => true

    =t.label :name
    =t.text_field :name

    = t.label :kind
    %br
    %br
    = t.radio_button :kind, 'rough'
    = t.label :kind, 'Rough', :value => 'Rough'
    = t.radio_button :kind, 'finish'
    = t.label :kind, 'Finish', :value => 'Finish'
    = t.radio_button :kind, 'threading'
    = t.label :kind, 'Threading', :value => 'Threading'

    %br
    %br
    =t.label :brand
    =t.text_field :brand

    =t.label :quantity
    =t.text_field :quantity

    =t.label :diameter
    =t.text_field :diameter

    =t.label :f_low
    =t.text_field :f_low

    =t.label :f_high
    =t.text_field :f_high

    =t.label :f_rough
    =t.text_field :f_rough

    =t.label :f_finish
    =t.text_field :f_finish

    =t.label :Vc_low
    =t.text_field :Vc_low

    =t.label :Vc_high
    =t.text_field :Vc_high

    =t.label :Vc_rough
    =t.text_field :Vc_rough

    =t.label :Vc_finish
    =t.text_field :Vc_finish

    =t.submit

#toolHolderForm{:style => "display:none",}
  %h1 Tool Holder
  =form_for @tool, html: { multipart: true } do |t|

    =t.label :name
    =t.text_field :name

    -# = t.label :kind
    %br
    %br
    = t.check_box :mill, id:"mill"
    = t.label "Mill", for:"mill", id:"mill"
    %br
    = t.check_box :lathe, id:"lathe"
    = t.label "Lathe", for:"lathe", id:"lathe"
    %br
    %br
    
    =t.label :brand
    =t.text_field :brand

    =t.label :quantity
    =t.text_field :quantity

    =t.label :diameter
    =t.text_field :diameter

    =t.label :length
    =t.text_field :length

    =t.label :teeth
    =t.text_field :teeth

    =t.label :fZ_low
    =t.text_field :fZ_low

    =t.label :fZ_high
    =t.text_field :fZ_high

    =t.label :fZ_rough
    =t.text_field :fZ_rough

    =t.label :fZ_finish
    =t.text_field :fZ_finish

    =t.label :Vc_low
    =t.text_field :Vc_low

    =t.label :Vc_high
    =t.text_field :Vc_high

    =t.label :Vc_rough
    =t.text_field :Vc_rough

    =t.label :Vc_finish
    =t.text_field :Vc_finish

    =t.submit

#drillForm{:style => "display:none",}
  %h1 Drill
  = form_for @tool do |t|
    =t.hidden_field :drill, :value => true

    =t.label :name
    =t.text_field :name

    =t.label :brand
    =t.text_field :brand

    =t.label :quantity
    =t.text_field :quantity

    = t.label :length
    %br
    %br
    = t.radio_button :drill_length, 'Extra Length'
    = t.label :drill_length, 'Extra Length', :value => 'Extra Length'
    = t.radio_button :drill_length, 'Jobber Length'
    = t.label :drill_length, 'Jobber Length', :value => 'Jobber Length'
    = t.radio_button :drill_length, 'Machine Screw'
    = t.label :drill_length, 'Machine Screw', :value => 'Machine Screw'
    %br
    %br
    =t.label :diameter
    =t.text_field :diameter

    =t.label :f_low
    =t.text_field :f_low

    =t.label :f_high
    =t.text_field :f_high

    =t.label :Vc_low
    =t.text_field :Vc_low

    =t.label :Vc_high
    =t.text_field :Vc_high

    =t.submit

%br
= button_to 'All Tools', tools_path, :class => "Button", :method => :get

:javascript
  function endmill() {
    console.log("endmill button hit");
    x = document.getElementById('endmillForm');
    if (x.style.display !== "contents"){
    x.style.display = "contents";}
    else {x.style.display = "none";}
    cancelOthers(endmillForm.id)
  }
  function turningTools() {
    console.log ("turning toool button hit");
    t = document.getElementById('turningToolsForm');
    if (t.style.display !== "contents"){
    t.style.display = "contents";}
    else {t.style.display = "none";}
    cancelOthers(turningToolsForm.id)
  }
  function drill() {
    console.log("drill button hit");
    d = document.getElementById('drillForm');
    if (d.style.display !== "contents"){
    d.style.display = "contents";}
    else {d.style.display = "none";}
    cancelOthers(drillForm.id)
  }
  function toolHolder() {
    console.log("tool holder button hit");
    tH = document.getElementById('toolHolderForm');
    if (tH.style.display !== "contents"){
    tH.style.display = "contents";}
    else {tH.style.display = "none";}
    cancelOthers(toolHolderForm.id)
  }
  function cancelOthers(form) {
    console.log("cancel other button if activated");
    var kindArray = ["drillForm", "endmillForm", "turningToolsForm", "toolHolderForm"];
    // a = kindArray.length
    for (i = 0; i < kindArray.length; i++)
      if (form == kindArray[i]){
      kindArray.splice(i,1)
      }
    kindArray.forEach(checkit);
  }
  function checkit(value) {
    //console.log(fullForm)
    ef = document.getElementById(value);
    if (ef.style.display !== "none" || ef.style.display === null){
    ef.style.display = "none"
    }
  }

app/views/tools/show.html.haml
%h1 Tools#show
%p Find me in app/views/tools/show.html.haml