config/routes.rb
Rails.application.routes.draw do
  resources :tools

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get 'dashboard/index'
  devise_for :users
  resources :users
  resources :timecards #do

  get "clock_out", to: "timecards#clock_out"
  get "clock_in", to: "timecards#clock_in"

  root 'home#index'

end

app/controllers/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @clockedin = Timecard.where(:user_id => current_user.id).last
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @clockedin = Timecard.where(:user_id => current_user.id).last
    @tools = Tool.all
    # binding.pry
    flash[:notice] = ("Meow")
    # toastr.info('welcome to the dashboard')
    # toastr["success"]("meow")
    # flash[:success] = t('.successfully_created')
    # toastr.info('Are you the 6 fingered man?')
  end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.haml
%h1 Shop Dashboard
%h3= "Welcome do the Dashboard #{current_user.email}"
= button_to 'Log out', destroy_user_session_path, method: :delete

-if current_user.superwizzard_role
  %h5 A super wizzard has arrived!
-elsif current_user.wizzard_role
  %h5 Wizzard man!
-else
  %h5 commoner

-if @clockedin == nil
  = button_to 'clocks-ins', clock_in_path, :class =>"Button", :method => :get

-elsif @clockedin.clockout.nil?
  = "Clock-in: #{@clockedin.clockin.strftime("%I:%M")}"
  %br
  = button_to 'clock-out', clock_out_path, :class =>"Button", :method => :get
  -# = @clockedin.clockin.strftime("%A, %b %d %Y %I:%M %z ")

-else
  = "Punch ID: #{@clockedin.id}"
  %br
  = "Clock-in: #{@clockedin.clockin.strftime("%I:%M")}"
  %br
  = "Clock-out: #{@clockedin.clockout.strftime("%I:%M")}"
  %br
  - ts = @clockedin.clockout - @clockedin.clockin
  - timeServed = ts.to_i / 60
  -# - timeServed = @clockedin.clockout.strftime("%I:%M") - @clockedin.clockin.strftime("%I:%M")
  = "Total: #{timeServed} minutes"
  %br
  = button_to 'clocks-ins', clock_in_path, :class =>"Button", :method => :get

%br
="Tools: #{@tools.count}"
= button_to 'all tools', tools_path, :class =>"Button", :method => :get
-# =@tools.any?